# Generated by Django 4.2.7 on 2023-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_objective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
