# Generated by Django 4.2.7 on 2023-12-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_tite',
            new_name='blog_title',
        ),
    ]
